### ISSUE TITLE
Maximum log entries when logging to memory?

### ISSUE THREAD

**Issue by rlenders** [elmah/Elmah#417]
I'm using Elmah to log errors in memory, remote access enabled. On my development machine, Elmah keeps track of as many logs as possible until I restart the application. However, in a release build, I can only see the last 15 logs. I understand Elmah only shows 15 logs per page, but in my release build there only ever is 1 page in with 15 errors in total. When a new error is logged, the oldest error disappears.

Is this a bug, or is it supposed to work this way?

**Comment by atifaziz** [comment]
The [default number of entires retained by the `MemoryErrorLog` is 15](https://github.com/elmah/Elmah/blob/1x/src/MemoryErrorLog.cs#L72-L77) so what you are seeing in release is accurate. You can change this via the `<errorLog>` element in your `web.config`:

```xml
<errorLog type="Elmah.MemoryErrorLog, Elmah" size="100" /> 
```

The [maximum value allowed for `size` is 500](https://github.com/elmah/Elmah/blob/1x/src/MemoryErrorLog.cs#L65-L70).

> On my development machine, Elmah keeps track of as many logs as possible until I restart the application.

If you're using the `MemoryErrorLog` on your development machine without any size configuration then it shouldn't differ from what you're observing in release.

**Comment by rlenders** [comment]
Ah, that explains my confusion. However, even though I am using the memory log without any size configuration, Elmah definitely shows more than just the last 15 entries.

**Comment by atifaziz** [comment]
As you can from (the source for `MemoryErrorLog`)[https://github.com/elmah/Elmah/blob/1x/src/MemoryErrorLog.cs], neither any special treatment for debug or release builds at run-time nor during compilation via conditional compilation symbols.

What version are you using?

If you manage to determine that this is indeed a bug with simple reproducible steps then please [file a new issue](https://github.com/elmah/Elmah/issues/new). Otherwise if your initial query is answered then consider closing this one.

**Comment by rlenders** [comment]
I'm using the `elmah.corelibrary` (v1.2.2) NuGet package, paired with `Elmah.Mvc` (v2.1.2).

I'll open a new issue if I can reproduce this in an empty project.
