### ISSUE TITLE
LogException raises ArgumentNullException

### ISSUE THREAD

**Issue by sepptruetsch** [elmah/Elmah#430]
Hi

We are having an issue were the Elmah.ErrorLogModule.LogException raises an System.ArgumentNullException because the passed in exception is null. 

The problem is this happens behinde the scenes and before any filtering occurs.
```json
[{
	"outerId": "0",
	"message": "Value cannot be null.\r\nParameter name: e",
	"type": "System.ArgumentNullException",
	"id": "61395811",
	"parsedStack": [{
			"method": "Elmah.ErrorLogModule.LogException",
			"level": 0,
			"assembly": "Elmah, Version=1.2.14706.0, Culture=neutral, PublicKeyToken=null",
			"line": 0
		}, {
			"method": "Elmah.ErrorLogModule.OnError",
			"level": 1,
			"assembly": "Elmah, Version=1.2.14706.0, Culture=neutral, PublicKeyToken=null",
			"line": 0
		}, {
			"method": "System.EventHandler.Invoke",
			"level": 2,
			"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
			"line": 0
		}, {
			"method": "System.Web.HttpApplication.RaiseOnError",
			"level": 3,
			"assembly": "System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a",
			"line": 0
		}
	]
}]
```

The function itself later on even has a comment  about swallowing any exception because logging should never throw any... Kind of contradictory not?
```
// IMPORTANT! We swallow any exception raised during the 
// logging and send them out to the trace . The idea 
// here is that logging of exceptions by itself should not 
// be  critical to the overall operation of the application.
// The bad thing is that we catch ANY kind of exception, 
// even system ones and potentially let them slip by.
```

So what are our options besides finding and fixing the issue which raised the error in the first place?

Thanks!

**Comment by atifaziz** [comment]
> So what are our options besides finding and fixing the issue which raised the error in the first place?

Your only option is to subclass `ErrorLogModule`, override `OnError` and and stop it from calling `LogException` if the last error is `null`, like so:

```c#
// assume:
// using System;
// using System.Web;

public class ErrorLogModule : Elmah.ErrorLogModule
{
    protected override void OnError(object sender, EventArgs args)
    {
        var application = (HttpApplication) sender;
        var error = application.Server.GetLastError();
        if (error == null)
            return;
        LogException(error, application.Context);
    }
}
```

Yet another implementation in a similar vein would be to simply override `LogException` instead and avoid delegating to the base implementation if the `e` (exception) argument is `null`:

```c#
public class ErrorLogModule : Elmah.ErrorLogModule
{
    protected override void LogException(Exception e, HttpContext context)
    {
        if (e == null)
            return;
        base.LogException(e, context);
    }
}
```

Register your sub-classed module instead of using the one supplied by ELMAH.

---
If this answers your question then please close the issue. Thanks.

**Comment by sepptruetsch** [comment]
Thanks for the quick answer!

We did replace the ErrorLogModule and check for null now. 
But still, is this thrown exception correct/wanted? In the spirit of exception logging not causing any exception?

Regards

**Comment by atifaziz** [comment]
> But still, is this thrown exception correct/wanted?

Honestly, it's very bizarre that ASP.NET should signal an error and not supply the exception. In 14 years since ELMAH was published, this is the first time anyone has reported this issue. The only thing I can imagine (though we don't see this in the stack trace) is that there may be another module in the pipeline that calls [`ClearError`][ClearError] during its handling of the [`Error`][Error] event and so by the time ELMAH's handler is called, it sees a `null` returned from [`GetLastError`][GetLastError]. I wonder if moving ELMAH up in the list of registered modules solves the problem?


[Error]: https://docs.microsoft.com/en-us/dotnet/api/system.web.httpapplication.error?view=netframework-4.7
[ClearError]: https://docs.microsoft.com/en-us/dotnet/api/system.web.httpserverutility.clearerror?view=netframework-4.7
[GetLastError]: https://docs.microsoft.com/en-us/dotnet/api/system.web.httpserverutility.getlasterror?view=netframework-4.7

**Comment by sepptruetsch** [comment]
Okay, I see this seems to be some weird/special case which we can handle ourself. 

Thanks for the help!
